spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:skka-for-test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    database: h2
  flyway:
    enabled: true
    encoding: UTF-8
    user: sa
    password:
    driver-class-name: org.h2.Driver

